% reglas(auto) generadas desde animals_rules.csv
% regla(Label, CondicionesComoLista).
regla(cat1, [true]).
regla(cat2, [true]).
regla(cat3, [true]).
regla(cat4, [true]).
regla(cat5, [true]).
regla(cat6, [true]).
regla(cat7, [true]).
regla(cat8, [true]).
regla(cat9, [true]).
regla(cat10, [true]).
regla(cat11, [true]).
regla(cat12, [true]).
regla(cat13, [true]).
regla(cat14, [true]).
regla(cat15, [true]).
regla(cat16, [true]).
regla(cat17, [true]).
regla(cat18, [true]).
regla(cat19, [true]).
regla(cat20, [true]).
regla(cat21, [true]).
regla(cat22, [true]).
regla(cat23, [true]).
regla(cat24, [true]).
regla(cat25, [true]).
regla(cat26, [true]).
regla(cat27, [true]).
regla(cat28, [true]).
regla(cat29, [true]).
regla(cat30, [true]).
regla(cat31, [true]).
regla(cat32, [true]).
regla(cat33, [true]).
regla(cat34, [true]).
regla(cat35, [true]).
regla(cat36, [true]).
regla(cat37, [true]).
regla(cat38, [true]).
regla(cat39, [true]).
regla(cat40, [true]).
regla(cat41, [true]).
regla(cat42, [true]).
regla(cat43, [true]).
regla(cat44, [true]).
regla(cat45, [true]).
regla(cat46, [true]).
regla(cat47, [true]).
regla(cat48, [true]).
regla(cat49, [true]).
regla(cat50, [true]).
regla(cat51, [true]).
regla(cat52, [true]).
regla(cat53, [true]).
regla(cat54, [true]).
regla(cat55, [true]).
regla(cat56, [true]).
regla(cat57, [true]).
regla(cat58, [true]).
regla(cat59, [true]).
regla(cat60, [true]).
regla(cat61, [true]).
regla(cat62, [true]).
regla(cat63, [true]).
regla(cat64, [true]).
regla(cat65, [true]).
regla(cat66, [true]).
regla(cat67, [true]).
regla(cat68, [true]).
regla(cat69, [true]).
regla(cat70, [true]).
regla(cat71, [true]).
regla(cat72, [true]).
regla(cat73, [true]).
regla(cat74, [true]).
regla(cat75, [true]).
regla(cat76, [true]).
regla(cat77, [true]).
regla(cat78, [true]).
regla(cat79, [true]).
regla(cat80, [true]).
regla(cat81, [true]).
regla(cat82, [true]).
regla(cat83, [true]).
regla(cat84, [true]).
regla(cat85, [true]).
regla(cat86, [true]).
regla(cat87, [true]).
regla(cat88, [true]).
regla(cat89, [true]).